[project]
name = "scipy-issue-blas-in-l-bfgs-b"
version = "0.1.0"
description = "Benchmark and profile SciPy L-BFGS-B performance"
readme = "README.md"
authors = [
    { name = "Hiroki Hamaguchi", email = "hari64boli64@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
]

[tool.uv]
package = false
